#!/usr/bin/env bash
# Refresh the Mozilla CA bundle shipped with Verium (curl/OpenSSL static builds).
# Source: https://curl.se/docs/caextract.html
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CERT_DIR="${ROOT}/src/certs"
URL="${CACERT_URL:-https://curl.se/ca/cacert.pem}"

mkdir -p "${CERT_DIR}"
curl -fsSL "${URL}" -o "${CERT_DIR}/cacert.pem"

python3 - "${CERT_DIR}/cacert.pem" "${CERT_DIR}/cacert_pem.inc" <<'PY'
import sys
from pathlib import Path
pem_path, inc_path = map(Path, sys.argv[1:3])
pem = pem_path.read_text()
if not pem.endswith("\n"):
    pem += "\n"
inc_path.write_text(
    "// Generated by contrib/certs/update-cacert.sh — Mozilla CA bundle (https://curl.se/docs/caextract.html)\n"
    "static const char EMBEDDED_CA_PEM[] = R\"cacert(" + pem + ")cacert\";\n"
)
print(f"Updated {pem_path} ({pem_path.stat().st_size} bytes)")
print(f"Updated {inc_path} ({inc_path.stat().st_size} bytes)")
PY
