name: Build Verium (Linux x86_64 • depends)

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: "Branch/Tag/SHA to build"
        required: true
        default: "Verium-1.3.5"
      depends_target:
        description: "Optional: build only this depends pkg first (e.g., boost, openssl). Leave empty for full depends."
        required: false
        default: ""
      verbose_make:
        description: "Verbose make output (V=1)"
        required: false
        default: "false"

concurrency:
  group: verium-linux
  cancel-in-progress: true

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  HOST_TRIPLET: x86_64-pc-linux-gnu

jobs:
  linux64:
    runs-on: ubuntu-22.04
    env:
      HOST_TRIPLET: x86_64-pc-linux-gnu
      # NEW: force toolchain to GCC 9 everywhere
      CC: gcc-9
      CXX: g++-9
          
      
    steps:
      - name: Checkout target ref
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_ref }}
          submodules: recursive
          fetch-depth: 0


      - name: Select GCC 9 toolchain (Linux)
        if: runner.os == 'Linux'
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y gcc-9 g++-9
          # Make gcc/g++ point to version 9 everywhere (covers scripts that hardcode 'gcc')
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-9 \
            --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 \
            --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9 \
            --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-9
          gcc --version
          g++ --version    

      - name: Base build deps (host)
        run: |
          set -euo pipefail
          sudo apt-get update
          # NEW: install gcc-9/g++-9
          sudo apt-get install -y \
            build-essential automake libtool pkg-config python3 \
            curl zip unzip ccache \
            gcc-9 g++-9
          "$CC" --version; "$CXX" --version

      - name: Build depends (Linux)
        run: |
          set -e
          if [ -n "${{ inputs.depends_target }}" ]; then
            echo "Priming depends target: ${{ inputs.depends_target }}"
            make -C depends HOST=${HOST_TRIPLET} \
              CC="$CC" CXX="$CXX" \
              ${{ inputs.depends_target }} -j"$(nproc || echo 2)"
          fi
          make -C depends HOST=${HOST_TRIPLET} \
            CC="$CC" CXX="$CXX" \
            -j"$(nproc || echo 2)" || {
              echo "---- tail any config.log ----"
              find depends/work/build -name config.log -exec sh -c 'echo "==> {}"; tail -n 120 "{}"' \;
              exit 1
            }

      - name: Configure (Linux)
        run: |
          set -e
          ./autogen.sh
          export CONFIG_SITE="$(pwd)/depends/${HOST_TRIPLET}/share/config.site"
          DEP="$(pwd)/depends/${HOST_TRIPLET}"
          # NEW: pass CC/CXX explicitly to configure
          CC="$CC" CXX="$CXX" ./configure \
            --host=${HOST_TRIPLET} \
            --prefix="$DEP" \
            --with-gui=qt5 \
            --with-qt-bindir="$DEP/native/bin" \
            --with-qt-incdir="$DEP/include" \
            --with-qt-libdir="$DEP/lib" \
            --disable-bench --disable-tests \
            --enable-reduce-exports \
            --disable-shared --enable-static

      - name: Build (Linux)
        run: |
          set -e
          if [ "${{ inputs.verbose_make }}" = "true" ]; then
            make CC="$CC" CXX="$CXX" -j"$(nproc || echo 2)" V=1
          else
            make CC="$CC" CXX="$CXX" -j"$(nproc || echo 2)"
          fi

      - name: Package + checksums (Linux)
        run: |
          set -euo pipefail
          V=$(git describe --tags --dirty --always || echo untagged)
          OUTDIR="out-linux"
          mkdir -p "$OUTDIR"
          cp -f src/verium* "$OUTDIR/" 2>/dev/null || true
          cp -f src/qt/verium* "$OUTDIR/" 2>/dev/null || true
          if [ -z "$(ls -A "$OUTDIR" 2>/dev/null)" ]; then
            echo "No Linux binaries found in $OUTDIR; exiting."
            exit 2
          fi
          PKG="verium-${V}-${HOST_TRIPLET}.tar.gz"
          tar -C "$OUTDIR" -czf "$PKG" .
          sha256sum "$PKG" > "${PKG}.SHA256SUMS"
          echo "ART_MAIN=$PKG" >> $GITHUB_ENV
          echo "ART_SUMS=${PKG}.SHA256SUMS" >> $GITHUB_ENV

      - name: Upload artifacts (binaries + checksums)
        uses: actions/upload-artifact@v4
        with:
          name: linux64-${{ env.HOST_TRIPLET }}
          path: |
            ${{ env.ART_MAIN }}
            ${{ env.ART_SUMS }}

      - name: Upload build logs (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-dep-logs
          path: |
            depends/work/build/**/config.log
            depends/work/build/**/config.status
          if-no-files-found: ignore
