name: Build Verium (Windows x86_64 • old-style)

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: "Branch/Tag/SHA to build"
        required: true
        default: "master"
      depends_target:
        description: "Optional: build only this depends pkg first (e.g., curl, openssl). Leave empty for full depends."
        required: false
        default: ""
      verbose_make:
        description: "Verbose make output (V=1)"
        required: false
        default: "false"

concurrency:
  group: verium-global
  cancel-in-progress: true

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  HOST_TRIPLET: x86_64-w64-mingw32

jobs:
  win64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout target ref
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_ref }} 
          submodules: recursive
          fetch-depth: 0

      - name: Base deps + MinGW toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential automake libtool pkg-config python3 \
            g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 \
            curl zip unzip ccache

      - name: Install GCC 9 (host) and select it
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y gcc-9 g++-9
          # make gcc-9/g++-9 the default host compilers
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
          gcc --version
          g++ --version

      - name: Cache depends (sources + built)
        uses: actions/cache@v4
        with:
          path: |
            depends/sources
            depends/built
          key: win-${{ env.HOST_TRIPLET }}-${{ hashFiles('depends/packages/*.mk') }}
          restore-keys: |
            win-${{ env.HOST_TRIPLET }}-

      - name: Patch curl.mk for MinGW (avoid AC_RUN; prefer WinSSL)
        run: |
          set -e
          f=depends/packages/curl.mk
          if [ -f "$f" ]; then
            if ! grep -q 'config_opts_mingw64.*with-winssl' "$f"; then
              {
                echo ''
                echo '# MinGW cross-friendly opts (added by CI)'
                echo '$(package)_config_opts += --disable-debug --disable-curldebug --disable-ldap --disable-ldaps --without-libidn2 --without-libpsl --without-brotli --without-zstd --without-nghttp2 --without-ssh --without-libssh2 --without-rtmp'
                echo '$(package)_config_opts_mingw32 += --with-winssl'
                echo '$(package)_config_opts_mingw64 += --with-winssl'
                echo '$(package)_conf_env += ac_cv_func_strerror_r=no ac_cv_strerror_r_char_p=no ac_cv_func_clock_gettime=no'
              } >> "$f"
            fi
          fi

      - name: Force MinGW POSIX threading model (safer std::thread/pthread)
        run: |
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

      - name: Hotfix headers (std::mutex / std::condition_variable)
        run: |
          set -e
          # Add <mutex> + <condition_variable> after <thread> in src/sync.h
          if [ -f src/sync.h ] && ! grep -q '<mutex>' src/sync.h; then
            awk '{
              print;
              if ($0 ~ /#include[[:space:]]*<thread>/) {
                print "#include <mutex>";
                print "#include <condition_variable>";
              }
            }' src/sync.h > src/sync.h.new && mv src/sync.h.new src/sync.h
          fi

          # Add <mutex> after <tinyformat.h> in src/logging.h
          if [ -f src/logging.h ] && ! grep -q '<mutex>' src/logging.h; then
            awk '{
              print;
              if ($0 ~ /#include[[:space:]]*<tinyformat\.h>/) {
                print "#include <mutex>";
              }
            }' src/logging.h > src/logging.h.new && mv src/logging.h.new src/logging.h
          fi

      - name: Force curl (7.62.0) to cross-compile cleanly on MinGW
        run: |
          set -euo pipefail
          f=depends/packages/curl.mk
          test -f "$f" || { echo "depends/packages/curl.mk not found"; exit 1; }

          # Teach curl.mk sane defaults for Windows cross builds
          perl -0777 -pe '
            s/(\$\(\s*package\s*\)_set_vars\s*\n)/$1# Cross-compile friendly opts for Windows\n$$(package)_config_opts += --disable-shared --enable-static --disable-ldap --disable-ldaps --without-libidn2 --without-libpsl --without-brotli --without-zstd --without-nghttp2 --without-ssh --without-libssh2 --without-rtmp\n$$(package)_config_opts_mingw32 += --with-winssl\n$$(package)_config_opts_mingw64 += --with-winssl\n$$(package)_conf_env += ac_cv_func_strerror_r=no ac_cv_strerror_r_char_p=no ac_cv_func_clock_gettime=no\n/;
          ' -i "$f"  

          # Start fresh for curl so the new options take effect
          rm -rf depends/work/build/*/curl/

      - name: Build depends (Win64)
        run: |
          set -e
          export RC=${HOST_TRIPLET}-windres
          export WINDRES=${HOST_TRIPLET}-windres

          if [ -n "${{ inputs.depends_target }}" ]; then
          echo "Priming depends target: ${{ inputs.depends_target }}"
          make -C depends HOST=${HOST_TRIPLET} \
          CC_FOR_BUILD=gcc-9 CXX_FOR_BUILD=g++-9 \
          ${{ inputs.depends_target }} -j"$(nproc || echo 2)" \
          RC="$RC" WINDRES="$WINDRES"
          fi

          make -C depends HOST=${HOST_TRIPLET} \
          CC_FOR_BUILD=gcc-9 CXX_FOR_BUILD=g++-9 \
          -j"$(nproc || echo 2)" RC="$RC" WINDRES="$WINDRES" || {
            echo "---- tail curl config.log ----"
            find depends/work/build -path "*/curl/*/config.log" -exec sh -c 'echo "==> {}"; tail -n 200 "{}"' \;
            echo "---- tail any config.log ----"
            find depends/work/build -name config.log -exec sh -c 'echo "==> {}"; tail -n 120 "{}"' \;
            exit 1
          }

      - name: Configure (Win64)
        run: |
          ./autogen.sh
          export CONFIG_SITE="$(pwd)/depends/${HOST_TRIPLET}/share/config.site"
          set -o pipefail
          ./configure \
            --host=${HOST_TRIPLET} \
            --prefix="$(pwd)/depends/${HOST_TRIPLET}" \
            --disable-bench --disable-tests \
            --enable-reduce-exports \
            --disable-shared --enable-static \
          || { echo "=== config.log (tail) ==="; tail -n 200 config.log || true; exit 1; }

      - name: Build (Win64)
        run: |
          if [ "${{ inputs.verbose_make }}" = "true" ]; then
            make -j"$(nproc || echo 2)" V=1
          else
            make -j"$(nproc || echo 2)"
          fi

      - name: Package + checksums (Win64)
        run: |
          set -euo pipefail
          V=$(git describe --tags --dirty --always || echo untagged)
          PKG="verium-${V}-${HOST_TRIPLET}.zip"
          mkdir -p out
          cp -f src/*.exe out/ 2>/dev/null || true
          cp -f src/qt/*.exe out/ 2>/dev/null || true
          [ -n "$(ls -A out)" ] || { echo "No Windows EXEs in out/"; exit 2; }
          (cd out && zip -r "../$PKG" .)
          sha256sum "$PKG" > "${PKG}.SHA256SUMS"
          echo "ART_MAIN=$PKG" >> $GITHUB_ENV
          echo "ART_SUMS=${PKG}.SHA256SUMS" >> $GITHUB_ENV

      - name: Upload artifacts (binaries + checksums)
        uses: actions/upload-artifact@v4
        with:
          name: win64-${{ env.HOST_TRIPLET }}
          path: |
            ${{ env.ART_MAIN }}
            ${{ env.ART_SUMS }}

      - name: Upload build logs (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: win64-dep-logs
          path: |
            depends/work/build/**/config.log
            depends/work/build/**/config.status
          if-no-files-found: ignore
